import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.ts",
  ],
  theme: {
    extend: {
      backgroundImage: {
        herobg: "url('/header-image.png')",
      },
      // backgroundSize: {
      //   "1440px": "1440px",
      // },
      fontFamily: {
        "dm-sans": "var(--font-dm-sans)",
        "font-poppins": "var(--font-poppins)",
        "font-roboto": "var(--font-roboto)",
      },
      fontSize: {
        hero: "5rem",
        headlineOne: "3rem",
        headlineTwo: "2.5rem",
        headlineThree: "2.125rem",
        headlineFour: "1.5rem",
        md: "16px",
      },
      gridTemplateColumns: {
        200: "repeat(2, 430px)",
        400: "repeat(2, 230px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        backgroundColor: "var(--background-color)",
        babyBlue20: "var(--baby-blue-20)",
        babyBlue40: "var(--baby-blue-40)",
        babyBlue60: "var(--baby-blue-60)",
        babyBlue80: "var(--baby-blue-80)",
        babyBlue100: "var(--baby-blue-100)",
        blue20: "var(--blue-20)",
        blue40: "var(--blue-40)",
        blue60: "var(--blue-60)",
        blue80: "var(--blue-80)",
        blue100: "var(--blue-100)",
        blue120: "var(--blue-120)",
        red20: "var(--red-20)",
        red40: "var(--red-40)",
        red60: "var(--red-60)",
        red80: "var(--red-80)",
        red100: "var(--red-100)",
        purple20: "var(--purple-20)",
        purple40: "var(--purple-40)",
        purple60: "var(--purple-60)",
        purple80: "var(--purple-80)",
        purple100: "var(--purple-100)",
        yellow20: "var(--yellow-20)",
        yellow40: "var(--yellow-40)",
        yellow60: "var(--yellow-60)",
        yellow80: "var(--yellow-80)",
        yellow100: "var(--yellow-100)",
        black20: "var(--black-20)",
        black40: "var(--black-40)",
        black60: "var(--black-60)",
        black80: "var(--black-80)",
        black100: "var(--black-100)",
        white100: "var(--white-100)",
        gray10: "var(--gray-10)",
        gray20: "var(--gray-20)",
        gray40: "var(--gray-40)",
        gray60: "var(--gray-60)",
        gray70: "var(--gray-70)",
        gray80: "var(--gray-80)",
        gray100: "var(--gray-100)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "var(--radius)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
