import type { Metadata } from "next";
import { DM_Sans, Poppins, Roboto } from 'next/font/google'
import "./globals.css";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";

const DMSans = DM_Sans({subsets: ["latin"], variable: '--font-dm-sans', weight: ["400", "500", "700"]});
const poppins = Poppins({subsets: ["latin"], variable: '--font-poppins', weight: ["400", "500", "700"]});
const roboto = Roboto({subsets: ["latin"], weight: ["400", "500", "700", "900"], variable: "--font-roboto"});

export const metadata: Metadata = {
  title: "TripGuide - Booking Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${DMSans.variable} ${poppins.variable} ${roboto.variable} antialiased`}
      >
       <div className="flex flex-col min-h-screen">
       <Header/>
        <div className="flex-1">
          {children}
        </div>
        <Footer/>
       </div>
      </body>
    </html>
  );
}
